os: linux

dist: xenail

language: c

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

install:
  cd ci/travis && ./configure && make && make install

before_script:
  - cd -
  - pip install --user cpp-coveralls

script:
  - cd ci/coveralls
  - make
  - ./test_all.out

after_success:
  - coveralls --exclude test/  --gcov-options '\-lp'
