language: c

compiler: gcc

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-6

install:
  cd ci/travis && ./configure && make && make install

script:
  - cd -
  - cd ci/coveralls/test
  - make
  - ./test_all.out

after_success:
  - coveralls --include ../src/ --gcov-options '\-lp'
