language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
install:
  cd ci/travis && ./configure && make && make install
script:
  - echo "script one"
  - echo "script two"

